# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-08 12:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Information',
        ),
    ]
